before_commands:
    - "composer install --prefer-source"
tools:
    external_code_coverage:
        timeout: 600
    php_code_coverage:
        enabled: true
        test_command: ./vendor/bin/phpunit
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths:
        - "tests/*"