language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - composer self-update
  - composer install --prefer-source --no-dev
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - find -type d -name vendor -prune -o -type f -name '*.php' -print0 | xargs -0 -n 1 php -l
  - phpcs -p --standard=PSR2 --extensions=php src tests
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover